config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'films#index'

  resources :films, only: %i[index show create new destroy] do
    resources :applauses, only: %i[create destroy]
  end
end

app/models/applause.rb
class Applause < ApplicationRecord
  belongs_to :film
  belongs_to :user

  validates :category, presence: true
  validates :category, uniqueness: { scope: [:film_id, :user_id] }

  enum category: %i[directing story cinematography sound acting]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :user
  has_many :applauses, dependent: :destroy

  validates :external_id, uniqueness: { scope: :source }
  validates :runtime, numericality: { greater_than: 0,
                                      less_than_or_equal_to: 50,
                                      only_integer: true ,
                                      message: 'can only be whole numbers between 0 and 50 minutes.'}

  enum source: [:youtube, :vimeo]
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user

  def self.admin?
    where(role_type: 'admin', active: true)
    .first
    .present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :films
  has_many :roles
  has_many :applauses
end

app/controllers/applauses_controller.rb
class ApplausesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    film = Film.find(params[:film])
    applause = film.applauses.create(user: current_user, category: params[:category])

    render json: { applause: 
                     { id: applause.id,
                       total: film.applauses.count},
                   film:
                     { id: film.id }
                 }
  end

  def destroy
    applause = current_user
                .applauses
                .where(id: params[:id])
                .first

    applause.destroy if applause

    render json: deleted_applause_json(applause)
  end

  private
    def deleted_applause_json(applause)
      return {} unless applause

      film = applause.film
      
      return { applause:
                 { total: film.applauses.count},
               film:
                 { id: film.id }
             }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
include Pagy::Backend

class FilmsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy new]

  def create
    link = film_params[:external_id]

    source_info = ExternalIDExtractor.new(link).perform
    film = current_user.films.build(film_params.merge(source_info)) if source_info.present?

    film.save ? flash[:success] = 'Film added' : flash[:error] = film.errors.full_messages.first

  rescue StandardError => e
    flash[:error] = e.message
  ensure
    redirect_to films_path
  end

  def index
    @pagy, @films = pagy(Film.all.order(created_at: :desc), items: 25)
  end

  def show
    @film = Film.find_by_id(params[:id])

    unless @film.present?
      flash[:error] = "Film not found"
      redirect_to films_path
    end
  end

  def destroy
    film = Film.where(id: params[:id]).first
    
    if film.nil?
      flash[:error] = "Film not found"
    elsif film.user_id == current_user.id || current_user.roles.admin?
      film.destroy
      flash[:success] = "Film removed"
    else
      flash[:error] = "You are not allowed to remove this film"
    end

    redirect_to films_path
  end

  def new
    @film = Film.new
    flash[:warning] = 'We currently only support YouTube, but we\'re working hard to integrate other sources.'
  end

  private
    def film_params
      params.require(:film).permit(:title, :runtime, :external_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/applauses_helper.rb
module ApplausesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
  include Pagy::Frontend
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applauses/_applause_buttons.html.erb
<button class="btn btn-outline-primary vote-collapse-button col-12"
  type="button"
  data-toggle="collapse"
  data-target="#voting-<%= film.id %>"
  aria-expanded="false"
  aria-controls="voting">
  <strong>Vote</strong>
</button>

<div class="collapse vote-collapse" id="voting-<%= film.id %>">
  <% Hash[Applause.categories.map { |k,_| [k,nil]}].merge(film.applauses.where(user: current_user).group_by(&:category)).each do |category, applause| %>
    <div class="row with-padding">
      <div class="col-2">
        <% if applause.present? %>
          <button class="btn btn-primary btn-round"
            data-film-id="<%= film.id %>"
            data-category="<%= category %>"
            data-category-id="<%= applause.first.id %>"
            data-method="DELETE"></strong><%= "\u2013" %></strong></button>
        <% else %>
          <button class="btn btn-outline-primary btn-round"
            data-film-id="<%= film.id %>"
            data-category="<%= category %>"
            data-method="POST"><strong>+</strong></button>
        <% end %>
      </div>
      <div class="col-10 category-vote-label"><%= category.upcase %>
        <% if  params[:action] == 'show' %>
          <strong data-film-id='<%= film.id %>' data-type="<%= category %> total">+ <%= film.applauses.where(category: category).count %></strong>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/applauses/_sign_in_redirect_buttons.html.erb
<%= button_to 'Vote',
  new_user_session_path,
  method: :get,
  class: 'btn btn-outline-primary vote-collapse-button col-12' %>

<div class="collapse vote-collapse">
  <% Applause.categories.each do |category| %>
    <div class="row with-padding">
      <div class="col-2">
        <%= button_to '+', new_user_session_path, method: :get, class: 'btn btn-outline-primary btn-round' %>
      </div>
      <div class="col-10 category-vote-label"><%= category.first.upcase %></div>
    </div>
  <% end %>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="/">ShortGems</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarLinks" aria-controls="navbarLinks" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarLinks">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Add Film', new_film_path, { class: 'nav-link' } %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to 'Log Out', destroy_user_session_path, { method: :delete, class: 'nav-link' } %>
        <% else %>
          <a class="nav-link" href="<%= new_user_session_path %>">Sign In</a>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/films/create.html.erb
<h1>Films#create</h1>
<p>Find me in app/views/films/create.html.erb</p>

app/views/films/destroy.html.erb
<h1>Films#destroy</h1>
<p>Find me in app/views/films/destroy.html.erb</p>

app/views/films/index.html.erb
<% @films.each do |film| %>
  <div class="row">
    <div class="col-12">
      <h2 style="font-family: Oswald;"><%= film.title %></h5>
      <h6 class="text-muted" style="font-family: Open Sans;"><%= film.runtime %> minutes</h6>
      <div class="row">
        <div class="col-sm-12 col-md-1">
          <div class="vote-total-wrapper">
            <strong data-film-id="<%= film.id %>" data-type="total">+ <%= film.applauses.count %></strong>
          </div>
        </div>
        <div class="video-col col-sm-12 col-md-7">
          <div class="video-container">
            <iframe
              frameborder="0"
              allow="autoplay; encrypted-media"
              allowfullscreen
              src="https://www.youtube.com/embed/<%= film.external_id %>">
            </iframe>
          </div>
        </div>
        <div class="col-sm-12 col-md-4">
          <% if user_signed_in? %>
            <%= render partial: 'applauses/applause_buttons', locals: { film: film } %>
          <% else %>
            <%= render partial: 'applauses/sign_in_redirect_buttons' %>
          <% end %>
        </div>
      </div>
      <% if current_user && (film.user_id == current_user.id || current_user.roles.admin?) %>
        <br />
        <%= link_to 'Remove film', film_path(film.id), { method: :delete, id: "remove-#{film.id}" } %>
      <% end %>
    </div>
  </div>
  <br />
  <br />
  <br />
<% end %>

<div class="pagination">
  <%== pagy_nav_bootstrap(@pagy) %>
</div>

<script>
  $('button').click(function() {
    applauseClick($(this));
  })
</script>

app/views/films/new.html.erb
<br />
<div class="row">
  <div class="card mx-auto">
    <div class="card-body">
      <h5 class="card-title">Add Film</h5>
      <%= form_for @film do |f| %>
        <div class="row">
          <div class="col-4">Title:</div>
          <div class="col-8"><%= f.text_field :title %></div>
        </div>
        <br />
        <div class="row">
          <div class="col-4">Runtime:</div>
          <div class="col-8"><%= f.number_field :runtime %></div>
        </div>
        <br />
        <div class="row">
          <div class="col-4">Link:</div>
          <div class="col-8"><%= f.text_field :external_id %></div>
        </div>
        <br />
        <div class="row">
          <div class="col-2"><%= f.submit 'Submit' %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/films/show.html.erb
<div class="row">
  <div class="col-12">
    <h2 style="font-family: Oswald;"><%= @film.title %></h5>
    <h6 class="texted-muted" style="font-family: Open Sans;"><%= @film.runtime %> minutes</h6>
    <div class="row">
      <div class="col-sm-12 col-md-1">
        <div class="vote-total-wrapper">
          <strong data-film-id="<%= @film.id %>" data-type="total">+ <%= @film.applauses.count %></strong>
        </div> 
      </div>
      <div class="video-col col-sm-12 col-md-7">
        <div class="video-container">
          <iframe
            frameborder="0"
            allow="autoplay; encrypted-media"
            allowfullscreen
            src="https://www.youtube.com/embed/<%= @film.external_id %>">
          </iframe>
        </div>
      </div>
      <div class="col-sm-12 col-md-4">
        <% if user_signed_in? %>
          <%= render partial: 'applauses/applause_buttons', locals: { film: @film } %>
        <% else %>
          <%= render partial: 'applauses/sign_in_redirect_buttons' %>
        <% end %>
      </div>
    </div>
    <% if current_user && (@film.user_id == current_user.id || current_user.roles.admin?) %>
      <br />
      <%= link_to 'Remove film', film_path(@film.id), { method: :delete, id: "remove-#{@film.id}" } %>
    <% end %>
  </div>
</div>

<script>
  $('button').click(function() {
    applauseClick($(this));
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortGems</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'navbar' %>
    <div class="container">
      <br />
      <% flash.each do |key, value| %>
        <% key = key == 'notice' ? 'info' : key %>
        <% key = key == 'alert' ? 'danger' : key %>
        <div class="alert alert-<%= key %> alert-dismissable fade show">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h3> Coming Soon </h3>
<h1> ShortGems </h1>